language: node_js

node_js:
  - "5"

env:
  global:
    - GITHUB_REPO: hackbellingham/member-graph
    - secure: oLaO2TMBYwwAf9GgUZbzs6lWDGE9Wn1hv/wfFoNwE0SGNczvG5C7HRDPd/bQxdyvGoylXef7SIjowdCfD/qxmPBqkdz5V7Jb136GinZtg1RTPicSddmm1wPEEGzN0GvOC7HshUGOAPXL0jPga04+N3kaydbGh0580RSDwZzi4gU9WnoDHPyVGoy6A79J70LAb8KP7BSNj46rBc2dmMspJyKyMGsEfyylAGNFO7HjSuPj7eUfcVTFj3shW2UzIhjIj5AXw0+QrYZtHOKRnWKps3qtStkyYKkzX/LJNxEkJfQIlMpq0veXhHmj2JOzHVYO35oxOWfL7Nne6fpdf4iLUmyhAVPGZN3OMLPvbVhopSZfaVxhMmGinsFO+3tUnhT7UIlC+YmyRD4mOtnbC03EVkHQkZm14Xb9mcvxAOj+gHK063o3mkB4L+BFWvTB8lvbHz+gxcBFEc5MzUAxkJW4XEPz5Jxth/HLw1DgsICxbs3/tSK/QbeVLNVa83NgaMLkiZWX2i/skvWpsGkTqYib++Dmpg7R/3jePgDQbCvaH0gX4q4JHKY7Ykie4iz6mA8vrTWj0pyrRRHFb1PlJKaWsddKAYDG/LebS9BE+SDlm21G7VgMijiv/oGLBhlvRYek0Opc9tttkLmYP9iiQIq9GSvk2jptIpb0j3oedBo0fKc=

script:
  - node ./scripts/process-links
  - node ./scripts/publish-github-pages 
